import { Flex } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Form from '../components/form';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <Flex
      w={'100%'}
      h={'100vh'}
      justifyContent={'center'}
      alignItems={'center'}
      my={{ base: '75px', md: '0' }}
    >
      <Head>
        <title>Sign In | Create an Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form />
    </Flex>
  );
};

export default Home;
